### PR TITLE
Handle KeyboardInterrupt gracefully

### PR DESCRIPTION
**Pull request by amoh-godwin**

### CODE REVIEW

**Comment by aiqc** [comment]
Thank you for submitting a PR! I am currently headed out for the day, but am looking forward to trying this later this evening.

**Comment by aiqc** [comment]
Did you happen to try this with `run_jobs(in_background=True)` ?

**Comment by amoh-godwin** [comment]
@aiqc Not yet. But I will try it out.

**Comment by aiqc** [comment]
We're all set. This is isolated from background processing. FYI background jobs are one is interrupted by `Batch.stop_jobs()`.

Thanks so much! Nice and simple!

**Pull request merged**
