### PR TITLE
moved config to another module

### PR DESCRIPTION
**Pull request by sahilgupta2105**
# Pull Request (PR) Template

## Does this solve an existing [Issue](https://github.com/aiqc/aiqc/issues)? 
- General refactoring

---

> *Put an `x` inside the applicable checkboxes `[ ]`.*

## Primary type of change:
- [ ] New feature.
- [ ] Bug fix.
- [ x] Refactor.
- [ ] Documentation.
- [ ] Build/ devops.
- [ ] Test.
- [ ] Other.

## Checklist:
- [x ] I have actually ran this code locally to make sure it works.
- [ x] I have pulled and merged the latest `main` into my feature branch.
- [ ] I have ran the existing [tests](https://github.com/aiqc/aiqc/new/main/.github#how-to-run-tests), and inspected areas that my code touches.
- [ ] I have updated the tests to include my changes.
- [ ] I have included updates to the documentation.
- [ ] I have built the documentation files `make html`.

> Describe the env you tested on: OS, Python version, shell type (e.g. cli, ide, notebook).

## Contains breaking changes:
- [ ] Yes (explain what functionality it breaks).
- [x ] No

### CODE REVIEW

**Review by Bennylave — APPROVED** [review]

**Comment by aiqc** [comment]
When I clone this, `aiqc.destroy_db()` with `rebuild=True` does not work for me.

**Comment by aiqc** [comment]
When I run `aiqc.setup`

```
---------------------------------------------------------------------------
ImproperlyConfigured                      Traceback (most recent call last)
<ipython-input-14-6ca6abb31d35> in <module>
----> 1 aiqc.setup()

~/Desktop/cloner/aiqc/aiqc/__init__.py in setup()
     58 #==================================================
     59 def setup():
---> 60 	setup_database([	File, Tabular, Image,
     61                         Dataset,
     62                         Label, Feature,

~/Desktop/cloner/aiqc/aiqc/configuration.py in setup_database(tablesToCreate)
    334         create_folder()
    335         create_config()
--> 336         create_db(tablesToCreate)

~/Desktop/cloner/aiqc/aiqc/configuration.py in create_db(tablesToCreate)
    295                 print(f"\n=> Info - skipping table creation as the following tables already exist.{tables}\n")
    296         else:
--> 297                 db.create_tables(tablesToCreate)
    298                 tables = db.get_tables()
    299                 table_count = len(tables)

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_tables(self, models, **options)
   3329     def create_tables(self, models, **options):
   3330         for model in sort_models(models):
-> 3331             model.create_table(**options)
   3332 
   3333     def drop_tables(self, models, **kwargs):

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_table(cls, safe, **options)
   6663             safe = options.pop('fail_silently')
   6664 
-> 6665         if safe and not cls._schema.database.safe_create_index \
   6666            and cls.table_exists():
   6667             return

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in database(self)
   5569         db = self._database or self.model._meta.database
   5570         if db is None:
-> 5571             raise ImproperlyConfigured('database attribute does not appear to '
   5572                                        'be set on the model: %s' % self.model)
   5573         return db

ImproperlyConfigured: database attribute does not appear to be set on the model: <Model: Algorithm>
```

**Comment by aiqc** [comment]
When I run `aiqc.destroy_db(confirm=True, rebuild=True)` I get this error:

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in execute_sql(self, sql, params, commit)
   3142             try:
-> 3143                 cursor.execute(sql, params or ())
   3144             except Exception:

OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

OperationalError                          Traceback (most recent call last)
<ipython-input-11-06a1dd422084> in <module>
----> 1 aiqc.destroy_db(confirm=True, rebuild=True)

~/Desktop/cloner/aiqc/aiqc/__init__.py in destroy_db(confirm, rebuild)
     70 
     71 def destroy_db(confirm:bool=False, rebuild:bool=False):
---> 72 	destroy_database([	File, Tabular, Image,
     73                         Dataset,
     74                         Label, Feature,

~/Desktop/cloner/aiqc/aiqc/configuration.py in destroy_database(tablesToCreate, confirm, rebuild)
    326 
    327                 if (rebuild==True):
--> 328                         create_db(tablesToCreate)
    329         else:
    330                 print("\n=> Info - skipping destruction because `confirm` arg not set to boolean `True`.\n")

~/Desktop/cloner/aiqc/aiqc/configuration.py in create_db(tablesToCreate)
    295                 print(f"\n=> Info - skipping table creation as the following tables already exist.{tables}\n")
    296         else:
--> 297                 db.create_tables(tablesToCreate)
    298                 tables = db.get_tables()
    299                 table_count = len(tables)

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_tables(self, models, **options)
   3329     def create_tables(self, models, **options):
   3330         for model in sort_models(models):
-> 3331             model.create_table(**options)
   3332 
   3333     def drop_tables(self, models, **kwargs):

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_table(cls, safe, **options)
   6668         if cls._meta.temporary:
   6669             options.setdefault('temporary', cls._meta.temporary)
-> 6670         cls._schema.create_all(safe, **options)
   6671 
   6672     @classmethod

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_all(self, safe, **table_options)
   5780     def create_all(self, safe=True, **table_options):
   5781         self.create_sequences()
-> 5782         self.create_table(safe, **table_options)
   5783         self.create_indexes(safe=safe)
   5784 

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in create_table(self, safe, **options)
   5635 
   5636     def create_table(self, safe=True, **options):
-> 5637         self.database.execute(self._create_table(safe=safe, **options))
   5638 
   5639     def _create_table_as(self, table_name, query, safe=True, **meta):

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in execute(self, query, commit, **context_options)
   3154         ctx = self.get_sql_context(**context_options)
   3155         sql, params = ctx.sql(query).query()
-> 3156         return self.execute_sql(sql, params, commit=commit)
   3157 
   3158     def get_context_options(self):

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in execute_sql(self, sql, params, commit)
   3148             else:
   3149                 if commit and not self.in_transaction():
-> 3150                     self.commit()
   3151         return cursor
   3152 

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in __exit__(self, exc_type, exc_value, traceback)
   2914             new_type = self.exceptions[exc_type.__name__]
   2915             exc_args = exc_value.args
-> 2916             reraise(new_type, new_type(exc_value, *exc_args), traceback)
   2917 
   2918 

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in reraise(tp, value, tb)
    188     def reraise(tp, value, tb=None):
    189         if value.__traceback__ is not tb:
--> 190             raise value.with_traceback(tb)
    191         raise value
    192 

~/.pyenv/versions/3.8.7/envs/jupyterlab3/lib/python3.8/site-packages/peewee.py in execute_sql(self, sql, params, commit)
   3141             cursor = self.cursor(commit)
   3142             try:
-> 3143                 cursor.execute(sql, params or ())
   3144             except Exception:
   3145                 if self.autorollback and not self.in_transaction():

OperationalError: disk I/O error
```

**Comment by aiqc** [comment]
@Bennylave @sahilgupta2105 in the morning I am going to reset the branch to June 23. 
https://github.com/aiqc/AIQC/commits/main

I am glad the initiative was taken to merge it, but I need to review it first for edge cases.

**Pull request merged**
