### PR TITLE
text dataset

### PR DESCRIPTION
**Pull request by sahilgupta2105**
[Issue](https://github.com/aiqc/aiqc/issues/13)

## Primary type of change:
- [x] New feature.
- [ ] Bug fix.
- [ ] Refactor.
- [ ] Documentation.
- [ ] Build/ devops.
- [ ] Test.
- [ ] Other.

## Checklist:
- [x] I have actually ran this code locally to make sure it works.
- [x] I have ran the existing [tests](https://github.com/aiqc/aiqc/new/main/.github#how-to-run-tests), and inspected areas that my code touches.
- [ ] I have updated the tests to include my changes.
- [ ] I have included updates to the documentation.
- [x] I am pushing a *branch*, not my *main/ master*.

> Describe the env you tested on: MacOs, Python 3.7.10

## Contains breaking changes:
- [ ] Yes (explain what functionality it breaks).
- [x] No

### CODE REVIEW

**Review by aiqc — APPROVED** [review]

**Comment by aiqc** [comment]
@sahilgupta2105 alright! we're rolling! thank you

How will the methods that read the Dataset always know where to find the text data? Something is missing in the `from_pandas` method.

Also, it would be good to make sure that the dtype of user-provided and aiqc-created dataframe TextData column is either np object or StringDtype:
https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html

**Comment by aiqc** [comment]
@sahilgupta2105 
also, since you are packing a dataframe in `from_strings` and `from_pandas` you should be able to make a `Dataset.Tabular.from_pandas()`. I think this would allow you to skip the raw `Dataset.create` and the File creation.

**Comment by sahilgupta2105** [comment]
> @sahilgupta2105 alright! we're rolling! thank you
> 
> How will the methods that read the Dataset always know where to find the text data? Something is missing in the `from_pandas` method.
> 
> Also, it would be good to make sure that the dtype of user-provided and aiqc-created dataframe TextData column is either np object or StringDtype:
> https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html

Do you mean the underlying table for text data? The reads would happen in the set of to_..() methods, right?

Sure, I will add a check for column datatype. Btw, what's the idea behind having an explicit dtype param for these functions? Isn't this something we can figure out from the input data?

**Comment by sahilgupta2105** [comment]
> @sahilgupta2105
> also, since you are packing a dataframe in both `from_strings` and `from_pandas` you should be able to call `Dataset.Tabular.from_pandas()`. I think this would allow you to skip the raw `Dataset.create` and the File creation.
> 
> Or did you have to do this in order to have 'dataset_type=text' defined?



> @sahilgupta2105
> also, since you are packing a dataframe in both `from_strings` and `from_pandas` you should be able to call `Dataset.Tabular.from_pandas()`. I think this would allow you to skip the raw `Dataset.create` and the File creation.
> 
> Or did you have to do this in order to have 'dataset_type=text' defined?

Yeah, most of the code in Text class looks very similar to the Tabular class. I don't have a good reason for having it there other than probably dataset_type=text. I can refactor this as I work through some of the other issues in this project and get better clarity on the overall API design. Please let me know if you have any recommendations, happy to explore those

**Comment by aiqc** [comment]
> Do you mean the underlying table for text data? 
So what I was getting at was that `from_pandas()` should check for:
```
if 'TextData' not in df.columns:
    raise ValueError("\nYikes - No column with the name 'TextData' was found in your dataframe.\n")
```
So that when it comes time to fetch the features, the system knows which column to use by default

**Comment by aiqc** [comment]
> Btw, what's the idea behind having an explicit dtype param for these functions?

It's to allow the user or system to force a dtype when ingesting data from file formats that don't do a great job at preserving dtypes like csv files.

Downstream aiqc processes get strict on dtypes. For example, regression requires a Label of np floating dtype. So I figured it would be good to help the user fix the problem w their data rather than just scold them.

**Comment by aiqc** [comment]
Unless you could allow the use to indicate which column in their df was the text column and record that somehow?

**Comment by sahilgupta2105** [comment]
Your comments make sense, let me fix these issues in the next pr

**Comment by sahilgupta2105** [comment]
> Unless you could allow the user to indicate which column in their df was the text column and record that somehow?

I think this is a good idea. We can give the user an option to specify this information as an optional parameter and then change the column name in their df to a standard one, like "TextData"? Also, do you think it makes sense to enforce the input data frame only to have a single input column, which would contain only strings?

**Pull request merged**
